# Generated by Django 3.0.3 on 2020-02-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='request_accept',
            field=models.NullBooleanField(),
        ),
    ]
