# Generated by Django 3.0.3 on 2020-02-13 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.ImageField(height_field=100, upload_to='Home/Projects/MinorProject/Images', width_field=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Property')),
            ],
        ),
    ]
