# Generated by Django 3.0.3 on 2020-02-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pic_name',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
