# Generated by Django 3.0.3 on 2020-02-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20200217_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic_name',
            field=models.ImageField(upload_to='images/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=30, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=30, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.CharField(max_length=30, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_on_rent',
            field=models.DateField(verbose_name='Rent start date'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tenure',
            field=models.DateField(blank=True, null=True, verbose_name='Tenure of rent'),
        ),
    ]
