# Generated by Django 3.0.3 on 2020-02-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_rent_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='is_active',
        ),
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
