# Generated by Django 3.0.3 on 2020-02-20 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_auto_20200220_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Property'),
        ),
    ]
