# Generated by Django 3.0.3 on 2020-02-20 11:09

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0009_auto_20200220_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'get_latest_by': builtins.id},
        ),
        migrations.AlterField(
            model_name='rent',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Property'),
        ),
    ]
