# Generated by Django 3.0.3 on 2020-02-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_auto_20200220_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
